### ISSUE TITLE
Pretty response output fails with larger data sets

### ISSUE THREAD

**Issue by orinocai** [MuShare/Httper-iOS#3] opened 2017-03-08 12:43 UTC
This app is great. I'm finding it very user-friendly and full-featured. Great that it's open source too!

However, I am having an issue with responses that return larger sets of data. The app takes a long time to process the result and in some cases it fails and the 'Pretty' tab is empty.

For example, the following GET requests return 10, 100 and 500 results respectively:

https://jsonplaceholder.typicode.com/users
https://jsonplaceholder.typicode.com/posts
https://jsonplaceholder.typicode.com/comments

If you try this in the app you should see that /users works fine, /posts takes a long time and /comments fails to populate the 'Pretty' tab.

I would love to help, but I'm not familiar with Swift, unfortunately.

**Comment by lm2343635** [comment] 2017-03-08 12:50
Thank you for your reply!
The problem you said about /posts and /comments may caused by the algorithm to format the response JSON string. I did not found a better open source algorithm by Swift language, so I have to implement it by myself. It may contains some problems, I will try to solve it.
Best wishes to you.

**Comment by lm2343635** [comment] 2018-06-18 10:03
Solves in this PR #21

**Comment by lm2343635** [comment] 2018-06-21 07:07
App Store version 2.3 has been updated.
Close this issue.

**Closed by lm2343635** 2018-06-21 07:07 UTC
